version: "3.9"
services:
  backend:
    image: manishsaraan/node-app:${TAG}
    container_name: node-backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_SECRET: ${STRIPE_SECRET}
